Repository Minywire/Bottlebrush_Engine, pull requests merged in 2024-05, with the labels that each got.

#111 Window System
  Bottlebrush_Engine/Bottlebrush_Engine/BBInput/CMakeLists.txt
  Bottlebrush_Engine/Bottlebrush_Engine/BBInput/Window.cpp
  Bottlebrush_Engine/Bottlebrush_Engine/BBInput/Window.h
  Bottlebrush_Engine/Bottlebrush_Engine/CMakeLists.txt
  Bottlebrush_Engine/Bottlebrush_Engine/EntryPoint.cpp
Labels: core, improvement

#114 89 ai init
  Bottlebrush_Engine/Bottlebrush_Engine/BBAI/CMakeLists.txt
  Bottlebrush_Engine/Bottlebrush_Engine/BBAI/FSM.cpp
  Bottlebrush_Engine/Bottlebrush_Engine/BBAI/FSM.h
  Bottlebrush_Engine/Bottlebrush_Engine/BBAI/NPC.cpp
  Bottlebrush_Engine/Bottlebrush_Engine/BBAI/NPC.h
  Bottlebrush_Engine/Bottlebrush_Engine/BBComponentSystem/CMakeLists.txt
  Bottlebrush_Engine/Bottlebrush_Engine/BBComponentSystem/Components.h
  Bottlebrush_Engine/Bottlebrush_Engine/BBComponentSystem/ECS.h
  Bottlebrush_Engine/Bottlebrush_Engine/BBComponentSystem/EntityFactory.cpp
  Bottlebrush_Engine/Bottlebrush_Engine/BBComponentSystem/EntityFactory.h
  Bottlebrush_Engine/Bottlebrush_Engine/BBComponentSystem/Systems.cpp
  Bottlebrush_Engine/Bottlebrush_Engine/BBComponentSystem/Systems.h
  Bottlebrush_Engine/Bottlebrush_Engine/BBResourceManager/CMakeLists.txt
  Bottlebrush_Engine/Bottlebrush_Engine/BBScene/Scene.cpp
  Bottlebrush_Engine/Bottlebrush_Engine/BBScene/Scene.h
  Bottlebrush_Engine/Bottlebrush_Engine/CMakeLists.txt
  Bottlebrush_Engine/Bottlebrush_Engine/EntryPoint.cpp
  Bottlebrush_Engine/Bottlebrush_Engine/Game/AI/States.lua
  Bottlebrush_Engine/Bottlebrush_Engine/Game/Cube.lua
  Bottlebrush_Engine/Bottlebrush_Engine/Game/exitCube.lua
Labels: core

#119 #115 ai movement
  Bottlebrush_Engine/Bottlebrush_Engine/BBAI/CMakeLists.txt
  Bottlebrush_Engine/Bottlebrush_Engine/BBAI/Movement.cpp
  Bottlebrush_Engine/Bottlebrush_Engine/BBAI/Movement.h
  Bottlebrush_Engine/Bottlebrush_Engine/BBAI/NPC.cpp
  Bottlebrush_Engine/Bottlebrush_Engine/BBAI/NPC.h
  Bottlebrush_Engine/Bottlebrush_Engine/BBComponentSystem/Components.h
  Bottlebrush_Engine/Bottlebrush_Engine/BBComponentSystem/EntityFactory.cpp
  Bottlebrush_Engine/Bottlebrush_Engine/BBComponentSystem/Systems.cpp
  Bottlebrush_Engine/Bottlebrush_Engine/BBComponentSystem/Systems.h
  Bottlebrush_Engine/Bottlebrush_Engine/BBScene/Scene.cpp
  Bottlebrush_Engine/Bottlebrush_Engine/BBScene/Scene.h
  Bottlebrush_Engine/Bottlebrush_Engine/BBScript/CMakeLists.txt
  Bottlebrush_Engine/Bottlebrush_Engine/BBScript/RegisterAIScripts.cpp
  Bottlebrush_Engine/Bottlebrush_Engine/BBScript/RegisterAIScripts.h
  Bottlebrush_Engine/Bottlebrush_Engine/Game/AI/States.lua
  Bottlebrush_Engine/Bottlebrush_Engine/Game/master_file.lua
Labels: core

#127 #118 state scripts
  Bottlebrush_Engine/Bottlebrush_Engine/BBComponentSystem/EntityFactory.cpp
  Bottlebrush_Engine/Bottlebrush_Engine/BBComponentSystem/Systems.cpp
  Bottlebrush_Engine/Bottlebrush_Engine/BBComponentSystem/Systems.h
  Bottlebrush_Engine/Bottlebrush_Engine/BBScene/Scene.cpp
  Bottlebrush_Engine/Bottlebrush_Engine/Game/AIStates/States.lua
  Bottlebrush_Engine/Bottlebrush_Engine/Game/NPCs/Patroller1.lua
  Bottlebrush_Engine/Bottlebrush_Engine/Game/NPCs/Patroller2.lua
  Bottlebrush_Engine/Bottlebrush_Engine/Game/master_file.lua
Labels: improvement

#131 #130 set npc to terrain height
  Bottlebrush_Engine/Bottlebrush_Engine/BBComponentSystem/Systems.cpp
  Bottlebrush_Engine/Bottlebrush_Engine/BBComponentSystem/Systems.h
  Bottlebrush_Engine/Bottlebrush_Engine/BBScene/Scene.cpp
Labels: core
